# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c68a1f69ecc11036d3b601f47635801331a744f944d6fd924cc4d7dfa6feeb95cf1f8aba81911dadb0a8ac9fe3692f7e969b4ac0ef31882c4a62bf47bb586095

test:
  secret_key_base: 1eeac17db9e84f01dcdb094b1a53672603a1a0d239df5c757daa551d6a88da5016477b916c1242684acbb99f590775617413cfb1160dcaa582c7279c918f8a4a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
